# Generated by Django 6.1.1 on 2026-10-05 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='ration_card_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='crop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.crop'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='crop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_crops', to='farmer.crop'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='crop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_crop_types', to='farmer.crop'),
        ),
    ]
